'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

# limit is 4000000

def fib():
    #create fib series list
    list_ = [1, 2]
    a, b = 1, 2
    while a+b <= 4000000:
        a, b = b, a+b
        list_.append(b)

    #add elements wtih modulo 2 == 0
    s = 0
    for i in list_:
        if i%2 == 0:
            s =  s + i
    return s
